uint8 SET_POSE=0
uint8 SET_PATH=1
uint8 SET_PARAMS=2
uint8 DELETE=3

uint8 action
string id
string type
geometry_msgs/Pose pose
geometry_msgs/Pose[] path
float64 path_velocity

string[] param_names
string[] param_values

---
string result_msg
